### ISSUE TITLE
Checkbox label moves when (un)checking

### ISSUE THREAD

**Issue by helb** [crazychicken/checkbox-radio#1]
The sudden label "jump" looks kinda weird:

![checkbox-1](https://cloud.githubusercontent.com/assets/178133/26300343/1b6733bc-3ede-11e7-8e3e-01e84a6a5312.gif)

Something like this might fit in better (achieved by `width: 1em` on the checkbox icon):

![checkbox-2](https://cloud.githubusercontent.com/assets/178133/26300487/837f43c2-3ede-11e7-93cd-38ba019ffc65.gif)

**Comment by crazychicken** [comment]
thank you for using checkbox-radio! i will fix it in next release
